
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url : jdbc:mariadb://localhost:3306/todo
    username : root
    password : green502

#my batis config
mybatis:
  type-aliases-package: com.example.todoapp
  mapper-locations: mappers/**/*.xml

  #swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/boardProjecEx

server:
  port: 8081